function [F, chan_map, t, Ts] = waread( fname )
%[F, chan_map, t, Ts] = waread( fname )
%
% Read "merged" channel data files as would be generated by merge2array.
%
%
% Scott Livingston  <slivingston@caltech.edu>
% 14 May 2010.

D = dir(fname);
if isempty(D)
    fprintf( 'Error: could not find file %s\n', fname );
    F = [];
    chan_map = [];
    return
end

fd = fopen( fname, 'r' );

chan_map = [];
while (1)
    chan_map(end+1) = fread(fd,1,'uint8');
    if length(chan_map)>1 && chan_map(end-1)==255 && chan_map(end)==255
        break
    end
end
chan_map(end-1:end) = [];
chan_map = chan_map';

startb = ftell(fd);
fseek(fd,0,'eof');
endb = ftell(fd);
fseek(fd,startb,'bof');
tsize = (endb-startb)/length(chan_map)/2;

F = zeros(tsize-1,length(chan_map));
for k = 1:length(chan_map)
    F(:,k) = fread(fd, tsize-1,'uint16' )';
    fread(fd,1,'uint16'); % eat the end-of-block marker
end

fclose(fd);

% for convenience, based on some parameter assumptions
Ts = 3.75e-6;
t = (1-size(F,1):0)*Ts';
